"""add new field to User model

Revision ID: ef17f950e487
Revises: 82566a0d93c3
Create Date: 2020-05-17 18:45:21.945941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef17f950e487'
down_revision = '82566a0d93c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('User', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'last_seen')
    op.drop_column('User', 'about_me')
    # ### end Alembic commands ###
